apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "oauth-proxy.fullname" . }}
  labels:
    {{- include "oauth-proxy.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "oauth-proxy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "oauth-proxy.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "oauth-proxy.serviceAccountName" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
          env:
            - name: TENANT_ID
              value: {{ required "settings.tenantId is required" .Values.settings.tenantId | quote }}
            - name: CLIENT_ID
              value: {{ required "settings.clientId is required" .Values.settings.clientId | quote }}
            - name: REDIRECT_URI
              value: {{ required "settings.redirectUri is required" .Values.settings.redirectUri | quote }}
            - name: SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "oauth-proxy.sessionSecretName" . }}
                  key: {{ .Values.sessionSecret.key | default "session-secret" }}
            - name: AZURE_FEDERATED_TOKEN_FILE
              value: {{ .Values.settings.federatedTokenFile | quote }}
            - name: SESSION_COOKIE_NAME
              value: {{ .Values.settings.sessionCookieName | quote }}
            - name: SESSION_COOKIE_SECURE
              value: {{ printf "%t" .Values.settings.sessionCookieSecure | quote }}
            - name: SESSION_COOKIE_SAMESITE
              value: {{ .Values.settings.sessionCookieSameSite | quote }}
            - name: SESSION_IDLE_TIMEOUT_SECONDS
              value: {{ printf "%d" .Values.settings.sessionIdleTimeoutSeconds | quote }}
            - name: SESSION_ABSOLUTE_TIMEOUT_SECONDS
              value: {{ printf "%d" .Values.settings.sessionAbsoluteTimeoutSeconds | quote }}
          {{- with .Values.settings.extraEnv }}
          {{ toYaml . | indent 12 }}
          {{- end }}
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.path }}
              port: http
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
            successThreshold: {{ .Values.livenessProbe.successThreshold }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.path }}
              port: http
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
